/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.glb --transform -d 
Files: room.glb [4.84MB] > C:\Users\Kayan Irani\OneDrive\Desktop\Just Coding\MyPortfolioWebsite\mainCode\models\room-transformed.glb [576.36KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Desk.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Mousepad.geometry} material={materials.MousepadMaterial} position={[-28.798, 0, 6.6]} scale={[5.47, 5.856, 5.876]} />
      <mesh geometry={nodes.Mouse.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Phone.geometry} material={materials.PhoneCover} />
      <mesh geometry={nodes.PhoneScreen.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.PhoneCamera.geometry} material={materials.Material} />
      <mesh geometry={nodes.USBPortInner.geometry} material={materials.PaletteMaterial003} position={[0, 0, -0.035]} />
      <mesh geometry={nodes.Frame_ComputerFrame_0.geometry} material={materials.ComputerFrame} position={[0, 0.976, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ComputerScreen.geometry} material={materials.ComputerScreen} position={[0, 0.65, -10.282]} rotation={[-Math.PI, 0, -Math.PI]} scale={[100, 113.4, 88.235]} />
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')
